name: Copy app-ads.txt to GitHub Pages Root

on:
  push:
    paths:
      - '**/app-ads.txt'
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy to root if not already
        run: |
          if [ -f "./app-ads.txt" ]; then
            echo "✅ app-ads.txt already in root"
          else
            FOUND=$(find . -name "app-ads.txt" | head -n 1)
            if [ -z "$FOUND" ]; then
              echo "❌ app-ads.txt not found anywhere!"
              exit 1
            fi
            cp "$FOUND" ./app-ads.txt
            echo "✅ Copied $FOUND to root"
          fi

      - name: Commit and Push root copy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add app-ads.txt
          git commit -m "자동 복사된 app-ads.txt" || echo "No changes to commit"
          git push
